### ISSUE TITLE
Change TOML layout format 

### ISSUE THREAD

**Issue by TimJones** [TimJones/godotty#25]
Switch format to use TOML sub-tables with names being source file by default e.g.

```toml
[dottyfile.file]
destination = "~/.file"

[dottyfile.other/file]
destination = "~/.config/otherfile"

# Allow for "name" if paths is silly long
[dottyfile.myfile]
source = "path/is/really/long/and/cumbersome/to/type/out/on/cli"
destination = ...
```
Should allow for simpler user-editing, also forces "source" dottyfile to be unambiguous & unique.
