### ISSUE TITLE
Add support for multiple profiles

### ISSUE THREAD

**Issue by TimJones** [TimJones/godotty#26]
Add support for using profiles when adding/removing dot files to godotty.
Be default profile name could match hostname, but should be override-able easily.
Could come with definitive list of files to mange, or maybe whitelist/blacklist would be better?

```toml
[profile.name]
dottyfiles = ["list", "of","dottyfiles"]

# or 
[profile.othername]
allowed_dottyfiles = [...]
disallowed_dottyfiles = [...]
```
